"""""""""""""""""""" NEOBUNDLE
if filereadable($HOME . "/.config/vim/plugins.vim")
  source $HOME/.config/vim/plugins.vim
endif

"""""""""""""""""""" GLOBAL
filetype plugin indent on
set background=dark
set relativenumber
set number
set mouse=a
let mapleader=","
set t_Co=256
syntax on
set encoding=utf-8
set hidden
" set nowrap
set breakindent
set backspace=indent,eol,start
set autoindent
set copyindent
set number
set shiftround
set ignorecase
set smartcase
set hlsearch
set incsearch
set history=1000
set undolevels=1000
set wildignore=*.swp,*.bak
set title
set visualbell
set noerrorbells
exec "set listchars=tab:⧽⧽,trail:⸰,nbsp:⸰"
set list
set ttyfast
set nocompatible
set backup
set backupdir=~/.cache/vim
set noswapfile
set fileformats=unix,dos,mac
set laststatus=2
set expandtab
set softtabstop=2 tabstop=2 shiftwidth=2
set ruler
set clipboard=unnamed

let g:jellybeans_background_color_256 = 232
colorscheme jellybeans


" Make Columns stand out
" highlight ColorColumn ctermbg=17
" call matchadd('ColorColumn', '\%81v', 100)
" call matchadd('ColorColumn', '\%101v', 100)

" Make comments italic
highlight Comment cterm=italic

"""""""""""""""""""" FILES SPECIFIC

au BufRead mutt-*        set ft=mail
au BufRead mutt-*        set invhls
au bufNewFile *.html 0r ~/.vim/templates/html.txt
au BufRead,BufNewFile *.jsm setfiletype javascript
au BufRead,BufNewFile *.xul setfiletype xml
au BufRead,BufNewFile *.md set ft=markdown
au BufRead,BufNewFile *.json set ft=json

autocmd filetype html,xml set listchars-=tab:>.
nnoremap <leader>j :%!jq .<CR>
nnoremap <leader>b :%!xxd<CR>

""""""""""""""" pastetoggle
" set pastetoggle=<F3>
map <F3> :set paste!<CR>

"Remove indenting on empty lines
map <F2> :%s/\s*$//g<cr>:noh<cr>''

nmap j gj
nmap k gk

cnoremap <C-a>  <Home>

set incsearch
set ignorecase
set smartcase
set hlsearch
nmap \q :nohlsearch<CR>

nmap <C-e> :e#<CR>

set showcmd

cmap \W !sudo tee % >/dev/null<CR>

" Colorpicker (only for mac)
inoremap <C-C> <C-R>=system('color-picker')<CR>

"""""""""""""""""""" KEYBINDINGS

map cc <leader>c<space>
map  <F6> :setlocal spell! spelllang=en<CR>
map  <F12> :set invhls<CR>
cmap <C-g> <C-u><ESC>
command! -bang W w<bang>
nnoremap <C-n> :bn<CR>
nnoremap <C-p> :bp<CR>
