"""""""""""""""""""" NEOBUNDLE
source $HOME/.config/vim/autoload/plug.vim

if filereadable($HOME . "/.config/vim/plugins.vim")
  source $HOME/.config/vim/plugins.vim
endif

"""""""""""""""""""" GLOBAL
filetype plugin indent on
set nostartofline
set scrolloff=8
set ttyfast
set background=dark
set relativenumber
set number
set mouse=a
let mapleader=","
set t_Co=256
syntax on
set encoding=utf-8
set hidden
" set nowrap
set breakindent
set backspace=indent,eol,start
set autoindent
set copyindent
set number
set shiftround
set ignorecase
set smartcase
set hlsearch
set incsearch
set history=1000
set undolevels=1000
set wildignore=*.swp,*.bak
set title
set visualbell
set noerrorbells
set listchars=tab:▸\ ,trail:⊗,nbsp:▹,eol:¬
set list
set nocompatible
set backup
set backupdir=$HOME/.cache/vim
set noswapfile
set fileformats=unix,dos,mac
set laststatus=2
set expandtab
set softtabstop=2 tabstop=2 shiftwidth=2
set ruler
set clipboard=unnamed
set lazyredraw
set cursorline

"let g:jellybeans_background_color_256 = 232
"let g:jellybeans_overrides = { 'SpecialKey': {'ctermfg' : '123', 'guifg': '#b4ecff'},}
let g:gruvbox_contrast_dark = 'hard'
let g:gruvbox_italicize_strings=1
let g:gruvbox_invert_signs=1
"colorscheme wells-colors
hi Conceal ctermfg=200
color dracula
set background=dark
highlight Normal ctermbg=NONE
highlight nonText ctermbg=NONE


" Make Columns stand out
" highlight ColorColumn ctermbg=17
" call matchadd('ColorColumn', '\%81v', 100)
" call matchadd('ColorColumn', '\%101v', 100)

set fillchars=vert:┃,fold:━
highlight VertSplit cterm=none ctermbg=none ctermfg=247

"""""""""""""""""""" FILES SPECIFIC

au BufRead,BufNewFile *.jsm setfiletype javascript
au BufRead,BufNewFile *.xul setfiletype xml
au BufRead,BufNewFile *.md set filetype=markdown
au BufRead,BufNewFile *.html set filetype=javascript
au BufRead,BufNewFile *.tag set filetype=javascript
au BufRead,BufNewFile *.json set filetype=json

nnoremap <leader>j :%!jq .<CR>
nnoremap <leader>b :%!xxd<CR>

""""""""""""""" pastetoggle
" set pastetoggle=<F3>
map <F3> :set paste!<CR>

"Remove indenting on empty lines
map <F2> :%s/\s*$//g<cr>:noh<cr>''

nmap j gj
nmap k gk

cnoremap <C-a>  <Home>

set incsearch
set ignorecase
set smartcase
set hlsearch
nmap \q :nohlsearch<CR>

nmap <C-e> :e#<CR>

set showcmd

cmap \W !sudo tee % >/dev/null<CR>

" Colorpicker (only for mac)
inoremap <C-C> <C-R>=system('color-picker')<CR>

"""""""""""""""""""" KEYBINDINGS

map cc <leader>c<space>
map  <F6> :setlocal spell! spelllang=en<CR>
map  <F12> :set invhls<CR>
cmap <C-g> <C-u><ESC>
command! -bang W w<bang>
nnoremap <C-n> :bn<CR>
nnoremap <C-p> :bp<CR>

""""""""""""""""""" Tab completion
function! Inserttabwrapper()
    let col = col('.') - 1
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<tab>"
    else
        return "\<c-p>"
    endif
endfunction

" Map <tab> to Inserttabwarpper()
inoremap <tab> <c-r>=Inserttabwrapper()<cr>

" Shift tab to backwards search
inoremap <s-tab> <c-n>

""""""""""""""""""" Strip bad whitespace
function! <SID>StripTrailingWhitespace()
    " Preparation: save last search, and cursor position.
    let _s=@/
    let l = line(".")
    let c = col(".")
    " Do the business:
    %s/\s\+$//e
    " Clean up: restore previous search history, and cursor position
    let @/=_s
    call cursor(l, c)
endfunction
nmap <Leader><space> :call <SID>StripTrailingWhitespace()<CR>

" RAML
autocmd! BufNewFile,BufRead *.raml set filetype=yaml

com! FormatJSON %!jq .

" Incsearch
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
