# Set directory variables
export SRC="${HOME}/.local/src"
export PRIVATE="${HOME}/.private"

# Source antigen
source ${SRC}/antigen/antigen.zsh

# Set locale properly
export LANG=en_US.UTF-8
export LC_NUMERIC=$LANG
export LC_ALL=$LANG

# Fixing PATH
PATH_START=$PATH
PATH="$HOME/.config/scripts"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/go/bin:$PATH"
PATH="/usr/local/opt/go/libexec/bin:$PATH"
PATH="/usr/local/bin:$PATH"
PATH="/usr/local/sbin:$PATH"
PATH="/sbin:$PATH"
PATH="/usr/sbin:$PATH"
PATH="$PATH:$PATH_START"
export PATH="$PATH:$PATH_START"

# Load private zshenv
[[ -f "${PRIVATE}/zshenv" ]] && source "${PRIVATE}/zshenv"

# OH-MY-ZSH stuff
antigen use oh-my-zsh
antigen bundles <<EOBUNDLES
  git
  git-extras
  extract
  pip
  lein
  command-not-found
  npm
  rbenv
  nvm
  brew
  bundler
  node
  brew-cask
  docker
  golang
  history
  urltools
  zsh-users/zsh-syntax-highlighting
  kennethreitz/autoenv
  seebi/dircolors-solarized
EOBUNDLES

# My theme
antigen theme mattbailey/pure pure

# End configuration.
antigen apply

# Set tabstops to 2 cols
tabs -2

# History settings
setopt hist_ignore_all_dups
setopt hist_ignore_space
export HISTSIZE=10000
export SAVEHIST=$HISTSIZE

# Default Editor
export EDITOR=vim

# vimpager
hash vimpager 2> /dev/null \
  && export PAGER=vimpager

# Docker
export DOCKER_HOST='tcp://127.0.0.1:2376'

# Handy aliases
alias chomp="tr -d '\n'"
alias ccwd="pwd | chomp | pbcopy"
alias -g 'sprunge'='curl -F "sprunge=<-" http://sprunge.us'

# NVM
hash brew 2> /dev/null \
  && source $(brew --prefix nvm)/nvm.sh \
  && export NVM_DIR=~/.nvm

# PyEnv
# if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Go
export GOPATH=${HOME}/go

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# gpg-agent is shitty
unset GPG_TTY

# Dircolors
hash gdircolors 2> /dev/null \
  && eval `gdircolors ~/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-seebi-SLASH-dircolors-solarized.git/dircolors.256dark`
hash dircolors 2> /dev/null \
  && eval `dircolors ~/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-seebi-SLASH-dircolors-solarized.git/dircolors.256dark`

# Don't let the last failure generate an exit code
echo -n ''
