# Set directory variables
export SRC="${HOME}/.local/src"
export PRIVATE="${HOME}/.private"

# make less better
export LESS="-F -X -R"

# Set locale properly
export LANG=en_US.UTF-8
export LC_NUMERIC=$LANG
export LC_ALL=$LANG

# Fixing PATH
PATH_START=$PATH
PATH="./node_modules/.bin"
PATH="$HOME/.config/scripts:$PATH"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/.linuxbrew/bin:$PATH"
PATH="$HOME/go/bin:$PATH"
PATH="/usr/local/opt/go/libexec/bin:$PATH"
#PATH="/usr/local/share/zsh/functions:$PATH"
PATH="/usr/local/bin:$PATH"
PATH="/usr/local/sbin:$PATH"
PATH="/sbin:$PATH"
PATH="/usr/sbin:$PATH"
PATH="/Developer/NVIDIA/CUDA-8.0/bin:$PATH"
PATH="~/anaconda3/bin:$PATH"
PATH="$PATH:$PATH_START"
export PATH="$PATH:$PATH_START"

# Pure config
#export PURE_PROMPT_SYMBOL=🍺

# Load private zshenv
[[ -f "${PRIVATE}/zshenv" ]] && source "${PRIVATE}/zshenv"

# Antibody https://getantibody.github.io/
#   brew install terminal-notifier hub httpie
source <(antibody init)
ZSH="$(antibody home)/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"
antibody bundle robbyrussell/oh-my-zsh
antibody bundle robbyrussell/oh-my-zsh folder:plugins/common-aliases
antibody bundle "
  robbyrussell/oh-my-zsh path:plugins/battery
  robbyrussell/oh-my-zsh path:plugins/brew
  robbyrussell/oh-my-zsh path:plugins/bgnotify
  robbyrussell/oh-my-zsh path:plugins/catimg
  robbyrussell/oh-my-zsh path:plugins/colored-man-pages
  robbyrussell/oh-my-zsh path:plugins/colorize
  robbyrussell/oh-my-zsh path:plugins/copybuffer
  robbyrussell/oh-my-zsh path:plugins/copydir
  robbyrussell/oh-my-zsh path:plugins/copyfile
  robbyrussell/oh-my-zsh path:plugins/docker
  robbyrussell/oh-my-zsh path:plugins/docker-compose
  robbyrussell/oh-my-zsh path:plugins/docker-machine
  robbyrussell/oh-my-zsh path:plugins/dotenv
  robbyrussell/oh-my-zsh path:plugins/emoji
  robbyrussell/oh-my-zsh path:plugins/emoji-clock
  robbyrussell/oh-my-zsh path:plugins/encode64
  robbyrussell/oh-my-zsh path:plugins/emotty
  robbyrussell/oh-my-zsh path:plugins/extract
  robbyrussell/oh-my-zsh path:plugins/git-extras
  robbyrussell/oh-my-zsh path:plugins/git
  robbyrussell/oh-my-zsh path:plugins/gitfast
  robbyrussell/oh-my-zsh path:plugins/github
  robbyrussell/oh-my-zsh path:plugins/golang
  robbyrussell/oh-my-zsh path:plugins/httpie
  robbyrussell/oh-my-zsh path:plugins/kubectl
  robbyrussell/oh-my-zsh path:plugins/minikube
  robbyrussell/oh-my-zsh path:plugins/mvn
  robbyrussell/oh-my-zsh path:plugins/nmap
  robbyrussell/oh-my-zsh path:plugins/node
  robbyrussell/oh-my-zsh path:plugins/npm
  robbyrussell/oh-my-zsh path:plugins/npx
  robbyrussell/oh-my-zsh path:plugins/osx
  robbyrussell/oh-my-zsh path:plugins/pip
  robbyrussell/oh-my-zsh path:plugins/python
  robbyrussell/oh-my-zsh path:plugins/react-native
  robbyrussell/oh-my-zsh path:plugins/redis-cli
  robbyrussell/oh-my-zsh path:plugins/rust
  robbyrussell/oh-my-zsh path:plugins/systemd
  robbyrussell/oh-my-zsh path:plugins/tig
  robbyrussell/oh-my-zsh path:plugins/vagrant
  robbyrussell/oh-my-zsh path:plugins/vault
  robbyrussell/oh-my-zsh path:plugins/yarn
  robbyrussell/oh-my-zsh path:plugins/urltools
  mafredri/zsh-async
  rupa/z
  seebi/dircolors-solarized
  sindresorhus/pure
  zsh-users/zsh-completions
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-syntax-highlighting
"

# Set tabstops to 2 cols
tabs -2

# History settings
setopt hist_ignore_all_dups
setopt hist_ignore_space
export HISTSIZE=100000
export SAVEHIST=$HISTSIZE

# Default Editor
export EDITOR=vim

# Handy aliases
alias clip="nc localhost 8377"
alias chomp="tr -d '\n'"
alias ccwd="pwd | chomp | pbcopy"
alias -g 'sprunge'='curl -F "sprunge=<-" http://sprunge.us'
alias https='http --default-scheme=https'

# PyEnv
# if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Go
export GOPATH=${HOME}/go

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS="-e -m"

# Rustup
[ -f ~/.cargo/env ] && source $HOME/.cargo/env

# gpg-agent is shitty
unset GPG_TTY

# Dircolors
hash gdircolors 2> /dev/null \
  && eval `gdircolors "$(antibody home)/https-COLON--SLASH--SLASH-github.com-SLASH-seebi-SLASH-dircolors-solarized/dircolors.256dark"`
hash dircolors 2> /dev/null \
  && eval `dircolors "$(antibody home)/https-COLON--SLASH--SLASH-github.com-SLASH-seebi-SLASH-dircolors-solarized/dircolors.256dark"`
[ -f `which gls` ] && alias ls='gls --color=auto'


fleetctl-switch(){
  export FLEETCTL_TUNNEL=$1:22
  alias etcdctl="ssh -A core@$1 'etcdctl'"
  alias fleetctl-ssh="fleetctl ssh $(fleetctl list-machines | cut -c1-8 | sed -n 2p)"
  RPROMPT="%{$fg[magenta]%}[fleetctl:$1]%{$reset_color%}"
}

start_mongo_replica(){
  CONTROL_IP=$1
  export FLEETCTL_TUNNEL=$CONTROL_IP:22
  ssh -A core@$CONTROL_IP 'etcdctl set /mongo/replica/name ci'
  FLEETCTL_TUNNEL=$1:22 fleetctl submit mongo@.service mongo-replica-config.service
  FLEETCTL_TUNNEL=$1:22 fleetctl start mongo@{1..3}.service
  FLEETCTL_TUNNEL=$1:22 fleetctl start mongo-replica-config.service
}

destroy_mongo_replica() {
  export FLEETCTL_TUNNEL=$1:22
  fleetctl destroy mongo@{1..3}.service
  fleetctl destroy mongo@.service
  fleetctl destroy mongo-replica-config.service

  etcdctl rm /mongo --recursive
  etcdctl set /mongo/replica/name ci

  echo 'Listing etcd /mongo dirs...'
  ssh -A core@$1 'etcdctl ls /mongo --recursive';

  echo Listing $1 /var/mongo
  ssh -A core@$1 'sudo rm -rf /var/mongo'

  echo Listing $2 /var/mongo
  ssh -A core@$2 'sudo rm -rf /var/mongo'

  echo Listing $3 /var/mongo
  ssh -A core@$3 'sudo rm -rf /var/mongo'
}

function install_jsctags {
  npm install jsctags
  # https://github.com/mozilla/doctorjs/issues/52
  gsed -i '51i tags: [],' ./node_modules/jsctags/jsctags/ctags/index.js
}

unset DOCKER_TLS_VERIFY
unset DOCKER_CERT_PATH
unset DOCKER_HOST
export CUDA_HOME=${HOME}/src/cuda
#export DYLD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-8.0/lib\
#                         ${DYLD_LIBRARY_PATH:+:${DYLD_LIBRARY_PATH}}
#export DYLD_LIBRARY_PATH=${HOME}/cuda:$DYLD_LIBRARY_PATH

export NVIM_TUI_ENABLE_TRUE_COLOR=1

zstyle ':completion:*' rehash true

#weather -z 99019 || exit 0

## VI-mode
#bindkey -v

# 10ms for key sequences
#KEYTIMEOUT=1

#test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
#[[ -f /Users/mbailey/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/mbailey/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
#[[ -f /Users/mbailey/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/mbailey/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh
export GHQ_ROOT=${HOME}/src
