# Set directory variables
export SRC="${HOME}/.local/src"
export PRIVATE="${HOME}/.private"

# make less better
export LESS="-F -X -R"

# Source antigen
source $(brew --prefix)/share/antigen/antigen.zsh

# Set locale properly
export LANG=en_US.UTF-8
export LC_NUMERIC=$LANG
export LC_ALL=$LANG

# Fixing PATH
PATH_START=$PATH
PATH="./node_modules/.bin"
PATH="$HOME/.config/scripts:$PATH"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/.linuxbrew/bin:$PATH"
PATH="$HOME/go/bin:$PATH"
PATH="/usr/local/opt/go/libexec/bin:$PATH"
PATH="/usr/local/bin:$PATH"
PATH="/usr/local/sbin:$PATH"
PATH="/sbin:$PATH"
PATH="/usr/sbin:$PATH"
PATH="$PATH:$PATH_START"
export PATH="$PATH:$PATH_START"

# Load private zshenv
[[ -f "${PRIVATE}/zshenv" ]] && source "${PRIVATE}/zshenv"

# OH-MY-ZSH stuff
antigen use oh-my-zsh
antigen bundles <<EOBUNDLES
  git
  git-extras
  extract
  brew
  brew-cask
  history
  urltools
  zsh-users/zsh-syntax-highlighting
  kennethreitz/autoenv
  seebi/dircolors-solarized
  mafredri/zsh-async
EOBUNDLES

# My theme
antigen theme mattbailey/pure pure

# End configuration.
antigen apply

# Set tabstops to 2 cols
tabs -2

# History settings
setopt hist_ignore_all_dups
setopt hist_ignore_space
export HISTSIZE=10000
export SAVEHIST=$HISTSIZE

# Default Editor
export EDITOR=vim

# Handy aliases
alias clip="nc localhost 8377"
alias chomp="tr -d '\n'"
alias ccwd="pwd | chomp | pbcopy"
alias -g 'sprunge'='curl -F "sprunge=<-" http://sprunge.us'
alias https='http --default-scheme=https'

# PyEnv
# if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Go
export GOPATH=${HOME}/go

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS="-e -m"

# Rustup
[ -f ~/.cargo/env ] && source $HOME/.cargo/env

# gpg-agent is shitty
unset GPG_TTY

# Dircolors
hash gdircolors 2> /dev/null \
  && eval `gdircolors ~/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-seebi-SLASH-dircolors-solarized.git/dircolors.256dark`
hash dircolors 2> /dev/null \
  && eval `dircolors ~/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-seebi-SLASH-dircolors-solarized.git/dircolors.256dark`

fleetctl-switch(){
  export FLEETCTL_TUNNEL=$1:22
  alias etcdctl="ssh -A core@$1 'etcdctl'"
  alias fleetctl-ssh="fleetctl ssh $(fleetctl list-machines | cut -c1-8 | sed -n 2p)"
  RPROMPT="%{$fg[magenta]%}[fleetctl:$1]%{$reset_color%}"
}

start_mongo_replica(){
  CONTROL_IP=$1
  export FLEETCTL_TUNNEL=$CONTROL_IP:22
  ssh -A core@$CONTROL_IP 'etcdctl set /mongo/replica/name ci'
  FLEETCTL_TUNNEL=$1:22 fleetctl submit mongo@.service mongo-replica-config.service
  FLEETCTL_TUNNEL=$1:22 fleetctl start mongo@{1..3}.service
  FLEETCTL_TUNNEL=$1:22 fleetctl start mongo-replica-config.service
}

destroy_mongo_replica() {
  export FLEETCTL_TUNNEL=$1:22
  fleetctl destroy mongo@{1..3}.service
  fleetctl destroy mongo@.service
  fleetctl destroy mongo-replica-config.service

  etcdctl rm /mongo --recursive
  etcdctl set /mongo/replica/name ci

  echo 'Listing etcd /mongo dirs...'
  ssh -A core@$1 'etcdctl ls /mongo --recursive';

  echo Listing $1 /var/mongo
  ssh -A core@$1 'sudo rm -rf /var/mongo'

  echo Listing $2 /var/mongo
  ssh -A core@$2 'sudo rm -rf /var/mongo'

  echo Listing $3 /var/mongo
  ssh -A core@$3 'sudo rm -rf /var/mongo'
}

function install_jsctags {
  npm install jsctags
  # https://github.com/mozilla/doctorjs/issues/52
  gsed -i '51i tags: [],' ./node_modules/jsctags/jsctags/ctags/index.js
}

unset DOCKER_TLS_VERIFY
unset DOCKER_CERT_PATH
unset DOCKER_HOST

export NVIM_TUI_ENABLE_TRUE_COLOR=1

#weather -z 99019 || exit 0
